{* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

Program      : 
Author       : n0mad
Module       : Defs.inc
Version      : 
Description  : 
Creation     : 12.10.2002 8:59:42
Installation : 


 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *}
{$DEFINE _NO_DEBUG}
{$DEFINE DemoX_DEBUG}
{$DEFINE _uMain_DEBUG}
{$DEFINE _uMain_Net_DEBUG}
{$DEFINE _uDatamod_DEBUG}
{$DEFINE _uDatamod_SQL_DEBUG}
{$DEFINE _uCells_DEBUG}
{$DEFINE uImports_DEBUG}
{$DEFINE _uPgbar_DEBUG}
{$DEFINE _uRescons_DEBUG}
{$DEFINE _uSetting_DEBUG}
{$DEFINE _uThreads_DEBUG}
{$DEFINE _uTools_DEBUG}
{$DEFINE uNet_DEBUG}
{$DEFINE _uPrint_DEBUG}

